{
 "title": "Salicru",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "generated_kW" } }
  ]
 },
 "panels": [
  { "title": "Instant", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Generation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "generated_kW{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Plant Performance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "generated_kW{instance=\"$Instance\"}",
     "legendFormat": "Generation"
    },
    {
     "expr": "generated_kW{instance=\"$Instance\"} + consumed_kW{instance=\"$Instance\"}",
     "legendFormat": "Consumption"
    }
   ]
  },
  {
   "title": "Max Generation",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "generated_kW{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Max Consumption",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consumed_kW{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "generated_kW{instance=\"$Instance\"} + consumed_kW{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Grid",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "consumed_kW{instance=\"$Instance\"}",
     "legendFormat": "Grid"
    }
   ]
  },
  {
   "title": "Grid",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consumed_kW{instance=\"$Instance\"}"
    }
   ]
  },
  { "title": "Daily", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Self",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "salicru_selfConsumption{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Self Generation",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(salicru_selfConsumption{instance=\"$Instance\"})/salicru_dailyGeneration{instance=\"$Instance\"}",
     "legendFormat": "Self generation"
    }
   ]
  },
  {
   "title": "Exported",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "salicru_export{instance=\"$Instance\"}",
     "legendFormat": "Exported"
    }
   ]
  },
  {
   "title": "Generation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "salicru_dailyGeneration{instance=\"$Instance\"}",
     "legendFormat": "Generation"
    }
   ]
  },
  {
   "title": "Self consumption",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(salicru_selfConsumption{instance=\"$Instance\"})/salicru_dailyConsumption{instance=\"$Instance\"}",
     "legendFormat": "Self consumption"
    }
   ]
  },
  {
   "title": "Imported",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "salicru_import{instance=\"$Instance\"}",
     "legendFormat": "Imported"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "salicru_dailyConsumption{instance=\"$Instance\"}",
     "legendFormat": "Consumption"
    }
   ]
  },
  {
   "title": "Daily savings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "salicru_moneySavingByGeneration{instance=\"$Instance\"}",
     "legendFormat": "by Generation"
    },
    {
     "expr": "salicru_moneySavingCompensation{instance=\"$Instance\"}",
     "legendFormat": "by Compensation"
    }
   ]
  }
 ]
}